export const cultures = [
  {
    code: 'en-US',
    languageName: 'English',
    countryName: 'United States',
    direction: 'ltr',
    currencyCode: 'USD',
    currencySymbol: '$',
    dashboardStyle: 'fintech-grid',
    theme: {
      background: '#edf5ff',
      surface: '#ffffff',
      surfaceSoft: '#dbeafe',
      text: '#0f172a',
      muted: '#475569',
      primary: '#2563eb',
      secondary: '#0f766e',
      accent: '#38bdf8',
      border: '#bfdbfe',
    },
    sampleCategories: ['Housing', 'Groceries', 'Transport', 'Investments'],
  },
  {
    code: 'ar-EG',
    languageName: 'Arabic',
    countryName: 'Egypt',
    direction: 'rtl',
    currencyCode: 'EGP',
    currencySymbol: 'E£',
    dashboardStyle: 'heritage-ledger',
    theme: {
      background: '#f8f1df',
      surface: '#fffaf0',
      surfaceSoft: '#ecdfbd',
      text: '#10253f',
      muted: '#5c5342',
      primary: '#0f766e',
      secondary: '#b8860b',
      accent: '#17324d',
      border: '#d9c89a',
    },
    sampleCategories: ['Household', 'Family', 'Transport', 'Savings'],
  },
  {
    code: 'fr-FR',
    languageName: 'French',
    countryName: 'France',
    direction: 'ltr',
    currencyCode: 'EUR',
    currencySymbol: 'EUR',
    dashboardStyle: 'editorial-minimal',
    theme: {
      background: '#f8f4ec',
      surface: '#fffdf8',
      surfaceSoft: '#eee5d7',
      text: '#172554',
      muted: '#5b6475',
      primary: '#1d3557',
      secondary: '#a33b42',
      accent: '#d7b98e',
      border: '#dbcdbb',
    },
    sampleCategories: ['Rent', 'Market', 'Dining', 'Travel'],
  },
  {
    code: 'de-DE',
    languageName: 'German',
    countryName: 'Germany',
    direction: 'ltr',
    currencyCode: 'EUR',
    currencySymbol: 'EUR',
    dashboardStyle: 'precision-ledger',
    theme: {
      background: '#f3f4f6',
      surface: '#ffffff',
      surfaceSoft: '#e5e7eb',
      text: '#111827',
      muted: '#4b5563',
      primary: '#111827',
      secondary: '#b91c1c',
      accent: '#d4a017',
      border: '#d1d5db',
    },
    sampleCategories: ['Rent', 'Mobility', 'Insurance', 'Reserves'],
  },
  {
    code: 'nl-NL',
    languageName: 'Dutch',
    countryName: 'Netherlands',
    direction: 'ltr',
    currencyCode: 'EUR',
    currencySymbol: 'EUR',
    dashboardStyle: 'bright-canal',
    theme: {
      background: '#eef6ff',
      surface: '#ffffff',
      surfaceSoft: '#e0f2fe',
      text: '#14324b',
      muted: '#476278',
      primary: '#f97316',
      secondary: '#2563eb',
      accent: '#0ea5e9',
      border: '#bfdbfe',
    },
    sampleCategories: ['Housing', 'Bike', 'Groceries', 'Leisure'],
  },
];

export const defaultCultureCode = 'en-US';

export const cultureStorageKey = 'masrofy.culture';

export function findCulture(code) {
  return cultures.find((culture) => culture.code === code) ?? cultures[0];
}
